In [26]:
import torch
import torch.nn as nn
import torchvision
from torchvision.models.resnet import ResNet18_Weights

from tta.data import build_loader, CifarDataset

In [27]:
dataset = CifarDataset()
dataset.prepare_dataset()
loader = build_loader(dataset)

In [28]:
model = torchvision.models.resnet18(weights=ResNet18_Weights.DEFAULT)

In [30]:
model(X)

tensor([[ 3.8211, -1.9410, -2.3917,  ..., 10.1764,  3.1401,  2.3415],
        [-3.0653,  1.7181, -2.2224,  ..., -1.4572, -3.2543,  7.5141],
        [ 1.5741, -2.1086,  2.9006,  ..., -4.3851,  1.8274,  0.6180],
        ...,
        [-4.9812, -1.0759, -2.4164,  ..., -3.5284,  2.5353,  0.8195],
        [-3.2497, -3.5549,  0.3088,  ..., -2.8721,  3.4812,  2.4813],
        [ 0.2326,  0.3305,  2.1131,  ...,  2.9349,  2.6403,  0.0407]],
       grad_fn=<AddmmBackward0>)

In [ ]:
for X, y, corrupt in loader:
    ## inference
    y_pred = model(X)
    
    ## ...

    ## ...

    ## ...

    ## evaluate
    
    break

In [19]:
X

tensor([[[[0.6784, 0.7176, 0.6980,  ..., 0.3765, 0.5373, 0.4392],
          [0.5373, 0.6588, 0.7373,  ..., 0.5765, 0.4196, 0.6196],
          [0.6000, 0.4392, 0.4980,  ..., 0.4588, 0.5569, 0.4392],
          ...,
          [0.2784, 0.1569, 0.1176,  ..., 0.1373, 0.0000, 0.1373],
          [0.2392, 0.1176, 0.1373,  ..., 0.1569, 0.0588, 0.1176],
          [0.2000, 0.2000, 0.1373,  ..., 0.0980, 0.1569, 0.1373]],

         [[0.4392, 0.6000, 0.4000,  ..., 0.3373, 0.1765, 0.3373],
          [0.5373, 0.4392, 0.4588,  ..., 0.2196, 0.4784, 0.3176],
          [0.4980, 0.4000, 0.4784,  ..., 0.3373, 0.3765, 0.3765],
          ...,
          [0.5373, 0.2196, 0.4784,  ..., 0.4588, 0.2000, 0.2588],
          [0.4980, 0.4196, 0.3373,  ..., 0.4784, 0.2784, 0.3373],
          [0.4392, 0.4588, 0.3176,  ..., 0.2588, 0.3373, 0.2588]],

         [[0.3373, 0.2392, 0.1569,  ..., 0.2000, 0.1176, 0.0588],
          [0.1176, 0.0000, 0.1569,  ..., 0.1373, 0.0784, 0.0784],
          [0.1765, 0.1765, 0.0980,  ..., 0

In [20]:
y

tensor([3, 8, 8, 0, 6, 6, 1, 6, 3, 1, 0, 9, 5, 7, 9, 8], dtype=torch.uint8)

In [21]:
corrupt

('shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise',
 'shot_noise')